### PR TITLE
cpp server session manager retry overhaul

### LINKED ISSUE #2920: Session Manager KV Cache Slot Allocation: Retry Tuning Under Oversubscription
## Summary

Benchmarking the SessionManager's KV cache slot allocation under oversubscription (128 concurrent users, 64 slots) reveals that the `SESSION_ALLOCATION_MAX_RETRIES` parameter has a critical impact on failure rate and tail latency. The current default of 10 retries causes significant request failures when users exceed the slot pool size.

## Test Setup

- **Server**: `tt_media_server_cpp` with `LLM_DEVICE_BACKEND=mock_pipeline`
- **Slot pool**: 64 slots (`MOCK_SLOT_POOL_SIZE=64`, `MAX_SESSIONS_COUNT=64`)
- **Benchmark**: `vllm bench serve` with 1000 prompts, random dataset (128 input / 128 output tokens)
- **Branch**: `dmadicTT/session-manager-harness` (includes `SlotPoolMemoryManager` and event recording)

### 64 concurrent users (baseline — no oversubscription)

| Metric | Value |
|---|---|
| Failed requests | **0** |
| Throughput | 85.85 req/s |
| Pool exhaustions | 0 |
| P99 TTFT | 769ms |

### 128 concurrent users (2x oversubscription)

| Metric | 10 retries (default) | 20 retries | 40 retries |
|---|---|---|---|
| **Failed requests** | **101** | **60** | **0** |
| Successful requests | 899 | 940 | 1000 |
| Pool exhaustions | 1,336 | 1,354 | 1,435 |
| Mean TTFT | 506ms | 413ms | 1,075ms |
| P99 TTFT | 5,052ms | 796ms | 12,178ms |
| Throughput (req/s) | 85.17 | 84.79 | 76.72 |
| Duration | 10.56s | 11.09s | 13.03s |

### Slot hold time (consistent across all retry configs)

| Metric | Value |
|---|---|
| p50 | ~720ms |
| p99 | ~1,080ms |
| max | ~1,230ms |

## Analysis

1. **Default retries (10) are insufficient under oversubscription**: With 10 retries x 500ms = 5s budget, ~10% of requests fail when users exceed slot count. The retry budget needs to be at least 2x the p99 slot hold time (~1,080ms) to reliably succeed.

2. **More retries eliminate failures but trade for tail latency**: 40 retries achieves 0 failures but P99 TTFT explodes to 12.2s. The retry loop's 500ms sleep between attempts means worst-case queuing of 20s.

3. **Throughput is bounded by token generation, not allocation**: All configs achieve ~85 req/s throughput. The slot allocation overhead is negligible compared to token generation time.

4. **Eviction works correctly**: Zero unknown deallocations across all runs. The LRU eviction successfully frees slots — the issue is purely timing (retry budget vs slot hold time).

## Recommendations

- **Consider adaptive retry backoff**: Instead of fixed 500ms sleep, use exponential backoff starting at a shorter interval (e.g., 50ms, 100ms, 200ms...) to succeed faster when a slot is about to free up.
- **Increase default retries**: Raise `SESSION_ALLOCATION_MAX_RETRIES` from 10 to at least 20 to reduce failures under moderate oversubscription.
- **Consider a waiting queue**: Instead of poll-retry, the SessionManager could maintain a FIFO queue of pending allocations that get fulfilled as slots become available, eliminating the retry storm entirely.

### PR DESCRIPTION
**Pull request by knovokmetTT**

### CODE REVIEW

**Review by dmadicTT — APPROVED** [review]

File: tt-media-server/cpp_server/include/config/defaults.hpp [hunk 1]
```diff
@@ -36,11 +36,11 @@ constexpr const char* KAFKA_BROKERS = "localhost:9092";
...
 constexpr const char* KAFKA_GROUP_ID = "migration-workers";
 
-constexpr unsigned SESSION_ALLOCATION_MAX_RETRIES = 10;
+constexpr unsigned SESSION_ALLOCATION_MAX_RETRIES = 15;
 constexpr unsigned PREFILL_TIMEOUT_MS = 10000;
 
-constexpr const char* H2D_SOCKET_ID = "deepseek_h2d";
-constexpr const char* D2H_SOCKET_ID = "deepseek_d2h";
+constexpr const char* H2D_SOCKET_ID = "deepseek";
+constexpr const char* D2H_SOCKET_ID = "deepseek";
```
Comment (ztorlakTT) [inline tt-media-server/cpp_server/include/config/defaults.hpp]: Could these two constants be collapsed into one (DEEPSEEK_SOCKET_BASE_ID) to make the intent clearer

File: tt-media-server/cpp_server/src/services/session_manager.cpp [hunk 2]
```diff
@@ -7,13 +7,35 @@
...
+namespace {
+constexpr std::chrono::milliseconds ALLOCATION_RETRY_BASE_DELAY{2000};
+constexpr std::chrono::milliseconds ALLOCATION_RETRY_DELAY_STEP{700};
+constexpr std::chrono::milliseconds ALLOCATION_RETRY_MAX_DELAY =
+    ALLOCATION_RETRY_BASE_DELAY +
+    ALLOCATION_RETRY_DELAY_STEP *
+        (tt::config::defaults::SESSION_ALLOCATION_MAX_RETRIES - 1);
+constexpr std::chrono::milliseconds IPC_QUEUE_FULL_RETRY_DELAY{50};
+
+inline std::chrono::milliseconds computeAllocationRetryDelay(int failureCount) {
```
Comment (ztorlakTT) [inline tt-media-server/cpp_server/src/services/session_manager.cpp]: `inline` inside an anonymous namespace has no effect
```suggestion
std::chrono::milliseconds computeAllocationRetryDelay(int failureCount) {
```

File: tt-media-server/cpp_server/src/services/session_manager.cpp [hunk 3]
```diff
@@ -7,13 +7,35 @@
...
 
 namespace tt::services {
 
+namespace {
+constexpr std::chrono::milliseconds ALLOCATION_RETRY_BASE_DELAY{2000};
+constexpr std::chrono::milliseconds ALLOCATION_RETRY_DELAY_STEP{700};
+constexpr std::chrono::milliseconds ALLOCATION_RETRY_MAX_DELAY =
+    ALLOCATION_RETRY_BASE_DELAY +
+    ALLOCATION_RETRY_DELAY_STEP *
+        (tt::config::defaults::SESSION_ALLOCATION_MAX_RETRIES - 1);
```
Comment (ztorlakTT) [inline tt-media-server/cpp_server/src/services/session_manager.cpp]: The hardcoded default SESSION_ALLOCATION_MAX_RETRIES = 15, but computeFailureCount reads the actual runtime value for sessionAllocationMaxRetries. If someone overrides the env var, the ALLOCATION_RETRY_MAX_DELAY will be wrong

**Review by idjuricTT — APPROVED** [review]
